# syntax=docker/dockerfile:1.7

ARG CORE_IMAGE=bitcoin-env/core-source:local
FROM ${CORE_IMAGE}

ARG NODE_ID
ARG NODE_ROLE

ENV NODE_ID=${NODE_ID} \
    NODE_NAME=node${NODE_ID} \
    NODE_ROLE=${NODE_ROLE}

COPY --chmod=0755 docker/entrypoint.sh /usr/local/bin/bitcoin-env-entrypoint
COPY --chmod=0755 controls/ /controls/
COPY --chmod=0755 scenarios/ /scenarios/

RUN set -eux; \
    test -n "$NODE_ID"; \
    test -n "$NODE_ROLE"; \
    chmod 0755 /controls/*.sh /scenarios/*.sh

ENTRYPOINT ["/usr/local/bin/bitcoin-env-entrypoint"]
